CREATE VIEW factory_product  AS
	SELECT FABRYKA.ID_fabryki as Identyfikator_Fabryki,    marka.NAZWA_MARKI ,model.NAZWA_MODELU
	FROM FABRYKA
	INNER JOIN MARKA ON FABRYKA.MARKA_ID_MARKI=MARKA.ID_MARKI
	INNER JOIN MODEL ON MARKA.ID_MARKI=MODEL.MARKA_ID_MARKI;

go